
global:
  scrape_interval: 3s

scrape_configs:
  - job_name: "job-express_metrics"
    static_configs:
      - targets: ["192.168.18.26:8000"]

  - job_name: "job-go-metrics"
    static_configs:
      - targets: ["192.168.18.26:9000"]
    
 # just host:port, no http:// and no path

